### ISSUE TITLE
Game OverScreen Overhaul

### ISSUE THREAD

**Issue by jdrueckert** [Terasology/LightAndShadow#130]
## Desired result
![image](https://user-images.githubusercontent.com/48293545/87904267-98f6af80-ca66-11ea-8002-c03d5f7f69e0.png)

## Tasks
- [x] Move skin file from LaS repo to LaSR repo - done in #128 
- [X] Update reference to skin file - done in #128 
- [x] Place all elements inside the shown boxes at the screenshot above - done in #136
- [x] Set `Game Over` and `Victory`/`Defeat` (currently `You Win!` and `You Lost!`(?)) UILabels to the top left - done in #136
- [x] Add `Hearts Team` and `Spades Team` labels - done in #136
- [x] Format spacing between details in the middle of the screen - done in #136
- [x] Add final score result _(the `Enemy Flags Captured` and points below that label)_ - done in #136
- [x] Change position of `Restart`, `Exit to Main Menu`, `Exit Terasology` and `Settings` buttons, based on the screenshot below  - done in #136
- [x] Add team symbol images before `Hearts Team` and `Spades Team` - done in #146 & https://github.com/Terasology/LightAndShadowResources/pull/56
- [x] Add wider images close to the bottom of the wider of the two boxes - done in #136
- [x] Set font sizes accordingly - done in #146 & https://github.com/Terasology/LightAndShadowResources/pull/56
- [x] Set new background images - done in #146 & https://github.com/Terasology/LightAndShadowResources/pull/56
- [x] Change button's design, according to the background, font color ect.. (?) - done in #146 & https://github.com/Terasology/LightAndShadowResources/pull/56
- [x] Add different font sizes - done in https://github.com/Terasology/LightAndShadowResources/pull/56
- [x] Asset, buttons and element placement - done in https://github.com/Terasology/LightAndShadow/pull/146 & https://github.com/Terasology/LightAndShadowResources/pull/56
- [x] Change font-color for `Victory`-`Defeat` label - done in https://github.com/Terasology/LightAndShadowResources/pull/57 & https://github.com/Terasology/LightAndShadow/pull/148
- [x] Add a border to outside UIBox - done in https://github.com/Terasology/LightAndShadow/pull/149 & https://github.com/Terasology/LightAndShadowResources/pull/58
- [ ] Place player names at the start of the column, and not at the middle of it
- [ ] Add point assets
- [ ] Add card assets that indicate the `Enemy Flags Captured`, like the mock-up

## How to test
1. Start a LaS game
2. Join a random team within the game
3. Score 5 points by capturing the other team's flag and bringing it to your base
4. The screen with the final score is the Game Over Screen, and will appear after scoring your 5th point
