### ISSUE TITLE
Score HUD Element Overhaul

### ISSUE THREAD

**Issue by jdrueckert** [Terasology/LightAndShadow#131]
## Desired result
![20200723_105544](https://user-images.githubusercontent.com/48293545/88284767-9f9b5600-ccf6-11ea-8a58-5285bc6af172.jpg)

## Tasks
- [x] Move skin file from LaS repo to LaSR repo - done in #129 
- [X] Update reference to skin file - done in #129 
- [x] Create a new design 
- [x] Place UIImage at the middle - WIP #138 
- [x] Place UILabels next to the current team scores, and connect it with `GOAL_SCORE` at `LASUtils.java` - WIP #138 
- [x] Place UI images next to the scores, indicating which score is which team's - WIP #138 
- [X] Create a PR for LASR, with the task to create and insert the Flag image in the middle of the UI - done https://github.com/Terasology/LightAndShadowResources/pull/47

## How to test
1. Start a LaS game
2. Notice the points at the top middle of the screen

**Comment by skaldarnar** [comment]
I think this one can be closed as **completed**!
