### ISSUE TITLE
Dialogue Screen Overhaul

### ISSUE THREAD

**Issue by jdrueckert** [Terasology/LightAndShadow#132]
## Current desired result
![image](https://user-images.githubusercontent.com/48293545/87910757-36f07700-ca73-11ea-91aa-af7c24fd7767.png)

## Tasks
- [X] Place dialogue box to the bottom left - done in #122 
- [X] Place answer choices to the right of the dialogue box - done in #122 
- [X] Add skin file to LaSR - done in https://github.com/Terasology/LightAndShadowResources/pull/45
- [X] Update reference to skin file - done in #122 
- [X] Add fool card asset to LASR - done in https://github.com/Terasology/LightAndShadowResources/pull/45
- [x] Insert `UIImage` to the left of the speech text within the box - done in #137
- [X] remove scrillableArea's background - WIP https://github.com/Terasology/LightAndShadowResources/pull/49
- [X] new dialogue box background - done in https://github.com/Terasology/LightAndShadowResources/pull/50
- [X] turn Fool's dialogue text from white to black - done in https://github.com/Terasology/LightAndShadowResources/pull/51
- [x] set ColumnLayout for the UIImages - done in https://github.com/Terasology/LightAndShadow/pull/139
- [x] add UIImages to new column according to prefab file - done in https://github.com/Terasology/Dialogs/pull/15
- [x] set a default asset for the answer button UIImage - done in https://github.com/Terasology/Dialogs/pull/15
- [x] set a custom asset for the answer button UIImage - done in https://github.com/Terasology/Dialogs/pull/15
- [x] create a binding of answer UIImages visibility and hovering over the answers - done in https://github.com/Terasology/Dialogs/pull/15
- [x] add a new column for the UIImages in the Dialogs module (other than the LAS module https://github.com/Terasology/LightAndShadow/pull/139) - done in https://github.com/Terasology/Dialogs/pull/15
- [x] insert new arrow asset - done in https://github.com/Terasology/Dialogs/pull/15
- [x] set UIImage to show the new arrow asset if the button next to it is hovered with the mouse - done in https://github.com/Terasology/LightAndShadowResources/pull/53 & https://github.com/Terasology/LightAndShadow/pull/156
- [ ] Edit answer button's background and font color/shadow - closed https://github.com/Terasology/Dialogs/pull/18 This shall be a UIButton feature
- [ ] `stretch goal` See if we can set the fool's image only when the fool is talking _(similar to how an asset is set when e.g. slot is active at quickslot)_ - different issue should be created for this one

## How to test
1. Start a LaS game
1. Talk to The Fool NPC feature in front of you
