### ISSUE TITLE
Inventory Overhaul

### ISSUE THREAD

**Issue by jdrueckert** [Terasology/LightAndShadow#134]
## Desired result
_under construction_

### Quickslot HUD Element
- [X] override Inventory module - done in #123 
- [X] move quickslot to the right of the screen - done in #123 
- [X] align the slots horizontally - done in #123 
- [X] change the order of the slot items from top-to-bottom to bottom-to-top - done in #123 
- [X] add feature to rotate items - done in https://github.com/Terasology/Inventory/pull/24
- [X] activate `rotateItems` within UI file - done in #126 
- [X] add vertical space between slot boxes - done in https://github.com/MovingBlocks/Terasology/pull/4089
- [x] add horizontal space between slot boxes - WIP https://github.com/MovingBlocks/Terasology/pull/4090
- [X] move skin file `inventoryLaS.skin` from LaS repo to LaSR repo - done in #133 & https://github.com/Terasology/LightAndShadowResources/pull/46
- [X] update reference to skin file - done in #133 
- [x] align smaller slot boxes to the right - done in https://github.com/MovingBlocks/Terasology/pull/4108 & https://github.com/Terasology/LightAndShadow/pull/141
- [x] create a new design - done in https://github.com/Terasology/LightAndShadowResources/pull/55

### Ammunition HUD Element
- [X] override CombatSystem `quiverHud.ui` module - done in #125  
- [X] move ammo slot next to the new possition of the quickslot - done in #125  
- [X] Add `Ammo` text above the slot - done in #125  
- [X] issue: ammo slot not appearing when game begins - resolved in https://github.com/Terasology/CombatSystem/pull/50
- [X] issue: figure out how to manipulate `UILabel`s - resolved at https://github.com/Terasology/LightAndShadow/pull/125#issuecomment-657079106
- [x] modify Ammo slot's placement - done in https://github.com/Terasology/LightAndShadowResources/pull/54
- [x] create a new design
- [x] use new design - done in https://github.com/Terasology/LightAndShadowResources/pull/59
- [x] reposition of UILabel based on background changes of InventoryCell - done in https://github.com/Terasology/LightAndShadow/pull/155

## How to test
1. Start a LAS game within Terasology (both new or old save is fine)
2. Fill up your quickslot with at least 2 items
3. Scroll up and down
