### ISSUE TITLE
In-Game Gameplay Instructions/Help for Players

### ISSUE THREAD

**Issue by jdrueckert** [Terasology/LightAndShadow#241]
## ToDos:

- [X] brainstorm and list first bunch of requirements
- [X] brainstorm and list first bunch of implementation options
- [ ] brainstorm and list first draft for instructions/help information content
- [X] first assessment of applicability of options with regards to requirements
- [ ] brainstorm and list first design drafts for presenting information
- [ ] add "extensibility" requirement (e.g. introduction of `Towers` might add more need for in-game help, but might need optional)

### :checkered_flag: Goal
Give the player some means to remember in-game how the gameplay works and what the important controls are

### :spiral_notepad: Requirements
- R1 - Accessible: easily and quickly accessible
- R2 - Intelligible: easy to understand, grasp and memorize
- R2 - Optional: on-demand, not mandatory to look at
- R3 - Maintainable: easy to adjust in case of key binding changes etc.

#### R1 - Accessible
- LaS is designed to be fast-paced game
- player does not have much time to access information without being attacked or losing momentum
- ideally permanently visible on screen or accessible with a single click or key stroke
- if not permanently visible, either non-blocking (surroundings still visible, movement still works, etc.) or only temporary access (i.e. timed or while holding a key)

#### R2 - Intelligible
- same time-related reasoning as for R1
- ideally player doesn't need to read a lot of text but is able to grasp info with single glance
  - no continuous text, bullet points at best
  - rather leverage icons, symbols, images
  - ideally have all information in one place, no multiple pages / tabs / screens the player needs to look through to find what they're looking for

#### R3 - Optional
- players that play frequently or have good memory don't need the information
- tutorials / screens that auto-start/-show and need to be explicitly skipped are annoying (IMO)
  - this kind of counters permanently visible solutions mentioned in R1

#### R4 - Maintainable
- key bindings, controls, gameplay elements can change
- if adjusting the instructions/help info is too complicated / too much effort it will end up not being done and we'll end up with incorrect and misleading instead of helpful information
- "too much effort" example: (non-vector) images with specific keys / controls that need to be re-drawn or fiddled with for instance in Gimp
  - icons / symbols might be simpler to replace

## :bulb: Solution Space
- S1: [`Books`](https://github.com/Terasology/Books)
- S2: [`Journal`](https://github.com/Terasology/Journal)
- S3: [`Notifications`](https://github.com/Terasology/Notifications)
- S4: [`Dialogs`](https://github.com/Terasology/Dialogs)
- S5: [`InGameHelp`](https://github.com/Terasology/InGameHelp)
- S6: Custom On-Demand UI Screen
- S7: Custom Permanent UI Screen
- S8: Loading Screen Hints
- S9: Conditional Screen Overlay
- S10: Other (?)

### S1 - [`Books`](https://github.com/Terasology/Books)

- item-based
- static information
- medium-sized UI screen

Screenshot from Lost (starting inventory item):
![image](https://user-images.githubusercontent.com/29981695/138361216-10585a38-f94f-4a85-8b54-fde7d1b4358b.png)

#### Accessible :heavy_minus_sign: :heavy_minus_sign: 
1. Optional: Open inventory, move item to quick access bar, close inventory
2. Select quick access slot with item
3. Right-click to bring up book screen
4. Click on page-turn arrow to see first content page

#### Intelligible :shrug: 
- medium-sized UI screen with two square content areas
- books are usually not a one-pager, so by design more suited for a lot of information or information that can be split well over multiple pages
- good for continuous text, full-page images
  - problematic with R2
- okay for bullet points, stylized use of icons or symbols
  - might work

#### Optional :heavy_plus_sign: :heavy_plus_sign:
- item can be present from start or given on request, for instance by fool
- takes up one inventory slot, but LaS is not inventory-space-heavy
- can be opened on-demand

#### Maintainable :shrug: 
- text-based book content is easily replaceable
- depends on how information is presented

### S2 - [`Journal`](https://github.com/Terasology/Journal)
- not item-based, dedicated key
- dynamic information
  - journal entries are designed to be activated over time / event-based
- large-sized UI screen

Screenshot from Lost (accessible on key "J"):
![image](https://user-images.githubusercontent.com/29981695/138365711-75c1b94d-5a34-4c8f-92a7-a13c9b28700b.png)

#### Accessible :heavy_plus_sign:
- one key stroke

#### Intelligible :shrug: 
- depends on way of presentation

#### Optional :heavy_plus_sign:
- control doesn't need to be used

#### Maintainable :shrug:
- depends on way of presentation

### S3 - [`Notifications`](https://github.com/Terasology/Notifications)
- not item-based
- dynamic information
  - can be triggered event-based, can be temporary or persistent (until end trigger, e.g. specific keystroke)
- small size UI screen

Screenshot from JoshariasSurvival (present at game start):
![image](https://user-images.githubusercontent.com/29981695/138365989-2f6840b6-b80b-49d7-85d5-249b6b5cd7b8.png)

#### Accessible :heavy_plus_sign: :heavy_plus_sign:
- assumption: always present on screen (after some on-demand trigger?)

#### Intelligible :heavy_minus_sign: 
- very small space to display information, more suited for individual key bindings / controls, less so for showing multiple at a single glance

#### Optional :shrug:
- can be done on-demand / optionally, but not sure if it's designed for the use case we have here :thinking: 

#### Maintainable :heavy_plus_sign:
- assumption: likely no images in use, but better maintainable ways of presenting information

### S4 - [`Dialogs`](https://github.com/Terasology/Dialogs)
- NPC-based
- static information
- small size UI screen

Screenshot from Light & Shadow (appears on talking to Fool (`E`) on spawn platform)
![image](https://user-images.githubusercontent.com/29981695/138366840-35ff6b8f-316e-4345-9904-03a49f0ff33e.png)

#### Accessible :heavy_minus_sign: :heavy_minus_sign: 
- needs an NPC to talk to

#### Intelligible :shrug: 
- depends on way of presentation

#### Optional :heavy_plus_sign: :heavy_plus_sign:
- dialogue doesn't need to be started

#### Maintainable :heavy_plus_sign:
- assumption: likely no images in use, but better maintainable ways of presenting information

### S5 - [`InGameHelp`](https://github.com/Terasology/InGameHelp)
- not item-based, dedicated key binding
- static information
- medium-sized UI screen

Screenshot from JoshariasSurvival (accessible on key "P"):
![image](https://user-images.githubusercontent.com/29981695/138367290-56fa06c8-c02c-469e-9dd8-ae30d6915ec9.png)

#### Accessible :heavy_plus_sign:
- single key stroke

#### Intelligible :shrug: 
- depends on way of presentation

#### Optional :heavy_plus_sign:
- control doesn't need to be used

#### Maintainable :shrug:
- depends on way of presentation

### S6 - Custom Temporary On-Demand UI Screen
- not item-based, dedicated key binding
- static or dynamic information
- variable size

Screenshot from Light & Shadow (accessible on key "G", try it out yourself to experience the "temporary" part):
![image](https://user-images.githubusercontent.com/29981695/138367523-de9d9e9a-7904-4111-9701-51968ed4b123.png)

#### Accessible :heavy_plus_sign:
- single key stroke (needs to be held)

#### Intelligible :shrug: 
- depends on way of presentation

#### Optional :heavy_plus_sign:
- control doesn't need to be used, screen doesn't stay open

#### Maintainable :shrug:
- depends on way of presentation

### S7 - Custom Permanent UI Widget
- can be item-based
- static or dynamic information
- variable, but likely small size

Screenshot from Metal Renegades ([`Minimap`](https://github.com/Terasology/Minimap)):
![image](https://user-images.githubusercontent.com/29981695/138368963-cf10b2d8-bd40-4232-a7aa-9cdb51f4239d.png)

#### Accessible :heavy_plus_sign: :heavy_plus_sign:
- permanently visible

#### Intelligible ( :heavy_minus_sign: )
- assumption: not enough space

#### Optional :heavy_plus_sign: / :heavy_minus_sign:
- if item-based, doesn't need to be selected :heavy_plus_sign:
- if permanently visible :heavy_minus_sign:

#### Maintainable ( :heavy_plus_sign: )
- assumption: likely no images in use, but better maintainable ways of presenting information

### S8 - Loading Screen Hints
- static information
- large-sized

Screenshot from Light & Shadow:
![image](https://user-images.githubusercontent.com/29981695/138366677-db468b54-24d0-4f64-a8bc-fbcaa1bdcbf4.png)

#### Accessible :heavy_minus_sign: :heavy_minus_sign: 
- not accessible in-game
  - not a real solution for the goal at hand, but might be a nice addition
- view time depends on loading time

#### Intelligible :shrug: 
- depends on way of presentation

#### Optional ( :heavy_minus_sign: )
- everybody goes through loading screen

#### Maintainable :heavy_minus_sign: :heavy_minus_sign:
- loading screens are images
- if we can add arbitrary text-based info then less problematic, but I don't think we currently have that functionality :thinking: 

### S9 - Conditional Screen Overlay
- based on location / proximity to specific things
  - not suitable for controls for things not present in the world
- typically used to give hints on controls
  - might not suitable for other kinds of information, e.g. gameplay process
- dynamic information
- small size

Screenshot from Light & Shadow (when coming close to the fool on the spawn platform):
![image](https://user-images.githubusercontent.com/29981695/138368465-18f69181-f6c9-4ac1-b325-36d49f28a49c.png)

#### Accessible ( :heavy_plus_sign: )
- condition needs to be met (e.g. standing close to fool)
  - controls-related info only really needed then anyway
  - players might wonder about lack of help as long as they're not satisfying condition

#### Intelligible :heavy_plus_sign:
- assumption: instructions clearly worded

#### Optional :heavy_minus_sign: :heavy_minus_sign: 
- can be done on-demand but requires effort that seems unnecessary

#### Maintainable :heavy_plus_sign:
- assumption: likely no images in use, but better maintainable ways of presenting information

**Comment by jdrueckert** [comment]
@ujjman Got a first version out, not sure how much time I'll have over the weekend to add more notes.

**Comment by jdrueckert** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [LaS - In-Game Help / Instructions](https://trello.com/c/UtNT5mJ0/187-las-in-game-help-instructions)

**Comment by ujjman** [comment]
I tried to make this possible using Journal module.
https://github.com/Terasology/LightAndShadow/pull/240
